version: 2 
jobs:
  build:
    docker:
      - image: circleci/node:1
    branches:
      only:
        - main
    steps:
      - add_ssh_keys:
          fingerprints:
          - "ea:ae:c9:c9:59:2f:e0:98:01:45:f9:e1:df:8f:a2:b4"
      - checkout
      - run: echo "first hello world"
      - run: npm -v
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build